config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_user_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReFormer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  <div>
<% end %>

<%= form_with model: @user, url: user_path, method: :patch, local: true do |form|%>
  <%= form.label :username, "Your name here:" %>
  <%= form.text_field :username, value: @user.username, label: "Y"%>
  <%= form.label :email, "Email:"%>
  <%= form.text_field :email, value: @user.email %>
  <%= form.label :password, "Password:"%>
  <%= form.password_field :password %>
  <%= form.submit "Submit"%>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, user %>
    </li>
  <% end %>
</ul>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  <div>
<% end %>

<%= form_with model: @user do |form| %>
  <%= form.label :username, "Your name here:" %>
  <%= form.text_field :username, value: "yourname", label: "Y"%>
  <%= form.label :email, "Email:"%>
  <%= form.text_field :email, placeholder: "example@example.com" %>
  <%= form.label :password, "Password:"%>
  <%= form.password_field :password %>
  <%= form.submit "Submit"%>
<% end %>

app/views/users/new_with_form_tag.html.erb
<%= form_tag("/users", method: "post") do %>
  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %>
  <%= label_tag(:email, "Email:") %>
  <%= text_field_tag(:email) %>
  <%= label_tag(:password, "Password:") %>
  <%= password_field_tag(:password) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/users/new_with_html_form.html.erb
<form accept-charset="UTF-8" action="/users" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="username">Username:</label>
  <input type="text" id="username" name="user[username]">
  <label for="email">Email:</label>
  <input type="text" id="email" name="user[email]">
  <label for="password">Password:</label>
  <input type="password" id="password" name="user[password]">
  <input type="submit" value="Submit">
</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p><%= @user.email %></p>
<p><%= @user.password %></p>

<%= link_to "Edit user data", edit_user_path%>